services:
  next:
    build:
      context: .
    env_file: ".env.docker"

    environment:
      NODE_ENV: production

    ports:
      - 127.0.0.1:3000:3000
    container_name: drillnext
    image: artempoletsky/interdrill

    volumes:
      - drill_database:/usr/src/app/kurgandb_data
    restart: on-failure
volumes:
  drill_database:
    external: true
