import './globals.css'
import '@mantine/core/styles.layer.css';
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })
import { ColorSchemeScript, MantineProvider, createTheme } from '@mantine/core';
import Layout from './components/PageLayout';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}


export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <head>
        <ColorSchemeScript />
        <script src="https://accounts.google.com/gsi/client" async></script>
      </head>
      <body className={inter.className}>
        <MantineProvider>
          <Layout>
            {children}
          </Layout>
        </MantineProvider>
      </body>
    </html>
  )
}
